name: Deploy (main)
on:
  repository_dispatch:
    types: [deploy-main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - id: pull-staging
        name: Pull latest 'staging'
        run: git pull origin staging

      - id: diff-check
        name: Check if 'main' is behind 'staging'
        run: git diff --exit-code origin/staging

      - id: fast-forward
        name: Fast forward 'staging' â†’ 'main'
        run: git merge --ff-only origin/staging

      - id: push-main
        name: Push latest 'main'
        run: git push --set-upstream origin main
