name: Deploy (testnet-dev)
on:
  pull_request:
    branches: [staging]
    types: [closed]
  push:
    branches: [testnet-dev]
  repository_dispatch:
    types: [deploy-testnet-dev]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - id: configure
        name: configure
        run: git config pull.ff true

      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: testnet-dev

      - id: pull-staging
        name: Pull latest 'staging'
        run: git pull origin staging

      - id: diff-check
        name: Check if 'testnet' is behind 'staging'
        run: git diff --exit-code origin/staging

      - id: fast-forward
        name: Fast forward 'staging' â†’ 'testnet-dev'
        run: git merge --ff-only origin/staging

      - id: push-testnet-dev
        name: Push latest 'testnet-dev'
        run: git push --set-upstream origin testnet-dev
