name: Tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npm test

  "e2e-test-noble-usdc-injective-inj":
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_interval: 15
          max_timeout: 1200
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config --system --add safe.directory /__w/ibc-dot-fun/ibc-dot-fun
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          WORD_PHRASE_KEY: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_USER: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_PASSWORD: ${{ secrets.POLKACHU_PASSWORD }}
          NEXT_PUBLIC_EDGE_CONFIG: ${{ secrets.NEXT_PUBLIC_EDGE_CONFIG }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
        run: xvfb-run --auto-servernum --server-args='-screen 0, 1920x1080x24' npm run test:e2e-1
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  "e2e-test-injective-inj-cosmoshub-atom":
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_interval: 15
          max_timeout: 1200
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config --system --add safe.directory /__w/ibc-dot-fun/ibc-dot-fun
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          WORD_PHRASE_KEY: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_USER: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_PASSWORD: ${{ secrets.POLKACHU_PASSWORD }}
          NEXT_PUBLIC_EDGE_CONFIG: ${{ secrets.NEXT_PUBLIC_EDGE_CONFIG }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
        run: xvfb-run --auto-servernum --server-args='-screen 0, 1920x1080x24' npm run test:e2e-2
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  "e2e-test-cosmoshub-atom-noble-usdc":
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_interval: 15
          max_timeout: 1200
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: git config --system --add safe.directory /__w/ibc-dot-fun/ibc-dot-fun
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          WORD_PHRASE_KEY: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_USER: ${{ secrets.WORD_PHRASE_KEY }}
          POLKACHU_PASSWORD: ${{ secrets.POLKACHU_PASSWORD }}
          NEXT_PUBLIC_EDGE_CONFIG: ${{ secrets.NEXT_PUBLIC_EDGE_CONFIG }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor200.outputs.url }}
        run: xvfb-run --auto-servernum --server-args='-screen 0, 1920x1080x24' npm run test:e2e-3
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
